### ISSUE TITLE
Annoy bot attacks by returning a delayed HTTP response

### ISSUE THREAD

**Issue by summercms** [summercms/sc-security-module#443]
### Enhancement idea

- [x] Annoy bot attacks by returning a delayed HTTP response. This reduces the amount of attacks they can run on the internet.

**Comment by ayumi-cloud** [comment]
https://www.w3schools.com/php/func_misc_sleep.asp

https://stackoverflow.com/questions/8882252/is-it-possible-to-delay-http-response-in-php

**Comment by ayumi-cloud** [comment]
https://laravel.com/docs/8.x/queues#delayed-dispatching

**Comment by ayumi-cloud** [comment]
Note: Some services have a max delay set, for example: 

The Amazon SQS queue service has a maximum delay time of 15 minutes.

The Cloudflare queue service has a maximum delay time of 30 minutes.
