### ISSUE TITLE
Update firewall to using summer cms parser module version 2

### ISSUE THREAD

**Issue by summercms** [summercms/sc-security-module#450]
### Enhancement idea

- [x] Update firewall to using summer cms parser module version 2. The update contains breaking changes and performance benefits to the firewall.

**Comment by ayumi-cloud** [comment]
repeat attacks

**Comment by summercms** [comment]
this->settingsConfigData->frontendLastBannedUA = hash('sha3-512', $this->FrontendData->userAgent);

**Comment by summercms** [comment]
Update `BadResponseHandling.php`

Sanitization modules connect
