### ISSUE TITLE
Process and check all validation fails on test sites

### ISSUE THREAD

**Issue by summercms** [summercms/sc-security-module#522]
### Enhancement idea

- [x] Process and check all validation fails on test sites.

**Comment by ayumi-cloud** [comment]
- 500 errors

**Comment by ayumi-cloud** [comment]
- Referer Types module not finished yet.

**Comment by summercms** [comment]
cleanDateTime

593

**Comment by summercms** [comment]
vals

components

**Comment by summercms** [comment]
crypto

main

**Comment by summercms** [comment]
turn on val checks on frontend test sites

**Comment by summercms** [comment]
meta hints updates

**Comment by summercms** [comment]
https://browserleaks.com/client-hints

**Comment by summercms** [comment]
https://github.com/WICG/ua-client-hints

**Comment by summercms** [comment]
https://web.dev/migrate-to-ua-ch/

**Comment by summercms** [comment]
..............running tests

**Comment by summercms** [comment]
3.108.66.199 is not in the database.

**Comment by summercms** [comment]
parser error -> bypass hash -> create log

**Comment by summercms** [comment]
hackingDesc 10k

**Comment by summercms** [comment]
check `int`

**Comment by summercms** [comment]
https://stackoverflow.com/questions/11245963/how-to-retrieve-complete-url-from-address-bar-using-php

**Comment by summercms** [comment]
https://tutorialio.com/get-the-full-url-of-current-page-in-php/
